xieyijvhua
Vincent-ice/5th-loongson-class-in-NEUQ pull request #22
Opened 2023-09-19 14:59 UTC by foxfxx-web

2023-09-20 02:21 UTC, Cai1Hsu requested changes
请先更新你的homework1分支

```bash
git fetch upstream
git merge upstrean/homework1
```

2023-09-21 02:20 UTC, Vincent-ice commented
- 请删除多余的文件夹
- 请将提交的文件放置于`./作业提交/`目录下

2023-09-21 02:48 UTC, Cai1Hsu commented
1. 删除子模块
```bash
git rm ./5th-loongson-class-in-NEUQ -r
```

2. 移动文件到 `./作业提交/` 目录下
```bash
mv ./week 1/作业提交/*.md ./作业提交/
```

2023-09-21 14:00 UTC, foxfxx-web commented
感谢大佬！！！

2023-09-21 14:38 UTC, Vincent-ice commented
文件目录还是不对啊
目录`./作业提交/`

2023-09-21 14:46 UTC, foxfxx-web commented
现在可以了吗






THE&nbsp;FH
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vincent-ice/5th-loongson-class-in-NEUQ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月21日(星期四) 晚上10:38
***@***.***&gt;;
抄送:&nbsp;"THE ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vincent-ice/5th-loongson-class-in-NEUQ] xieyijvhua (PR #22)





 
文件目录还是不对啊
 目录./作业提交/
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-09-21 14:48 UTC, merged